# Generated by Django 4.2.5 on 2023-10-08 17:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileHasDetectedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_detected_ip", models.CharField(max_length=15, null=True)),
                ("last_detected_continent", models.CharField(max_length=15, null=True)),
                ("last_detected_country", models.CharField(max_length=15, null=True)),
                ("last_detected_city", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=users.models.uuid_generator, editable=False
                    ),
                ),
                ("username", models.CharField(max_length=20, null=True, unique=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Your email address",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Your password", max_length=50, null=True
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Full user's birth date", null=True
                    ),
                ),
                ("year_of_birth", models.IntegerField(help_text="User's birth year")),
                ("first_name", models.CharField(max_length=25, null=True)),
                ("last_name", models.CharField(max_length=35, null=True)),
                ("signature", models.CharField(max_length=150, null=True)),
                ("about_text", models.TextField(max_length=20, null=True)),
                ("city_of_birth", models.CharField(max_length=25, null=True)),
                ("country_of_birth", models.CharField(max_length=25, null=True)),
                ("continent_of_birth", models.CharField(max_length=15, null=True)),
                ("country_today", models.CharField(max_length=25, null=True)),
                ("citizenship_1", models.CharField(max_length=25, null=True)),
                ("citizenship_2", models.CharField(max_length=25, null=True)),
                ("number_of_publications", models.IntegerField(default=0)),
                ("prefered_country", models.CharField(max_length=25, null=True)),
                ("prefered_city", models.CharField(max_length=25, null=True)),
                ("prefered_continent", models.CharField(max_length=25, null=True)),
                ("best_stay", models.CharField(max_length=255, null=True)),
                ("profile_picture", models.URLField(null=True)),
                ("background_picture", models.URLField(null=True)),
                ("motto", models.CharField(max_length=55, null=True)),
                ("last_detected_data", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
