# Generated by Django 4.2.5 on 2023-10-22 19:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profilefollowers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="number_of_publications",
            new_name="user_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="about_text",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="background_picture",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="best_stay",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="citizenship_1",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="citizenship_2",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="city_of_birth",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="continent_of_birth",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="country_of_birth",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="country_today",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_detected_data",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="motto",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="prefered_city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="prefered_continent",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="prefered_country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="signature",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="year_of_birth",
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="blank-profile-picture.jpg",
                null=True,
                upload_to="profile_images",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(
                default=users.models.uuid_generator, editable=False, null=True
            ),
        ),
    ]
