# Generated by Django 4.2.5 on 2023-10-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="password",
            field=models.CharField(
                help_text="Your password", max_length=255, null=True
            ),
        ),
    ]
