# Generated by Django 4.2.5 on 2023-10-29 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_profile_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_id",
        ),
    ]
