# Generated by Django 4.2.5 on 2023-11-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_profile_is_active_profile_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_text",
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="motto",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="season_of_birth",
            field=models.CharField(default="Spring", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="signature",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="year_of_birth",
            field=models.IntegerField(default=1900, help_text="User's birth year"),
        ),
    ]
