# Generated by Django 4.2.5 on 2023-11-11 21:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_profile_about_text_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(
                default=models.UUIDField(
                    default=users.models.uuid_generator, editable=False, null=True
                ),
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
