# Generated by Django 4.2.5 on 2023-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
