# Generated by Django 4.2.5 on 2023-11-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="motto",
            field=models.CharField(default="I LOVE THIS WEBSITE!", max_length=100),
        ),
    ]
