# Generated by Django 4.2.5 on 2023-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_profile_motto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about_text",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
