# Generated by Django 4.2.5 on 2023-11-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_profile_about_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about_text",
            field=models.TextField(default="Once upon a time...", null=True),
        ),
    ]
