# Generated by Django 4.2.5 on 2023-12-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_profilehasdetecteddata_connected_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, unique=False),
        ),
    ]
