# Generated by Django 4.2.5 on 2023-12-03 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_alter_profile_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="slug",
        ),
    ]
