# Generated by Django 4.2.5 on 2023-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(
                default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
