# Generated by Django 4.2.5 on 2023-12-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_alter_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="blank-profile-picture.jpg",
                null=True,
                upload_to="uploads/<django.db.models.fields.SlugField>/profile_images",
            ),
        ),
    ]
