# Generated by Django 4.2.5 on 2023-12-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="blank-profile-picture.jpg",
                null=True,
                upload_to="uploads/profile_pictures",
            ),
        ),
    ]
