# Generated by Django 4.2.5 on 2023-12-24 16:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="blank-profile-picture.jpg",
                null=True,
                upload_to=users.models.profile_picture_upload_to,
            ),
        ),
    ]
