# Generated by Django 4.2.5 on 2023-12-25 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileHasPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="ProfileFollowers",
            new_name="ProfileHasFollower",
        ),
        migrations.CreateModel(
            name="ConnectionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "On-line"), ("offline", "Off-line")],
                        default="online",
                        max_length=10,
                    ),
                ),
                ("first_login", models.DateTimeField(auto_now_add=True)),
                ("last_echo", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "device_id")},
            },
        ),
    ]
