# Generated by Django 4.2.4 on 2023-12-31 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_profilehaspublication_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfileHasDetectedData",
        ),
    ]
