# Generated by Django 4.2.4 on 2024-01-01 03:13

import core.utils.models_helpers
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_imageofgallery_delete_seasonhaspublication_and_more"),
        ("users", "0032_profilehaspublication_publication_of_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilehasfollower",
            name="profile_username",
            field=core.utils.models_helpers.SlugFieldForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profilehaspublication",
            name="publication_of_user",
            field=core.utils.models_helpers.UUIDForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.publication",
            ),
        ),
        migrations.AlterField(
            model_name="profilehaspublication",
            name="user_profile",
            field=core.utils.models_helpers.SlugFieldForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
