# Generated by Django 4.2.4 on 2024-01-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_alter_profilehasfollower_profile_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="ProfileHasFollower",
        ),
    ]
