# Generated by Django 4.2.4 on 2024-01-01 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0034_profile_is_online_delete_profilehasfollower"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="devices",
            field=models.ManyToManyField(to="users.device"),
        ),
    ]
