# Generated by Django 4.2.4 on 2024-01-01 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0035_device_profile_devices"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        choices=[(True, "Online"), (False, "Offline")], default=False
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ConnectionHistory",
        ),
    ]
