# Generated by Django 4.2.4 on 2024-01-01 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_connectionstatus_delete_connectionhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="devices",
        ),
        migrations.DeleteModel(
            name="Device",
        ),
    ]
