# Generated by Django 4.2.4 on 2024-01-01 21:18

import core.utils.models_helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0037_remove_profile_devices_delete_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionstatus",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="connectionstatus",
            name="profile",
            field=core.utils.models_helpers.SlugFieldForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="slug",
            ),
        ),
    ]
