# Generated by Django 4.2.4 on 2024-01-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_alter_connectionstatus_is_online_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="continent_of_birth",
            field=models.CharField(
                choices=[
                    ("OC", "Oceania"),
                    ("EU", "Europe"),
                    ("AF", "Africa"),
                    ("NA", "North America"),
                    ("AN", "Antarctica"),
                    ("SA", "South America"),
                    ("AS", "Asia"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
