# Generated by Django 4.2.4 on 2024-01-01 22:14

import core.utils.models_helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_profile_continent_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionstatus",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="Online Status"),
        ),
        migrations.AlterField(
            model_name="connectionstatus",
            name="profile",
            field=core.utils.models_helpers.SlugFieldForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_status",
                to=settings.AUTH_USER_MODEL,
                to_field="slug",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="Online Status"),
        ),
        migrations.AlterUniqueTogether(
            name="connectionstatus",
            unique_together={("profile", "is_online")},
        ),
    ]
