# Generated by Django 4.2.4 on 2024-01-02 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0041_alter_connectionstatus_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionstatus",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
