# Generated by Django 4.2.4 on 2024-01-04 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0042_alter_connectionstatus_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConnectionStatus",
        ),
    ]
