# Generated by Django 4.2.4 on 2024-01-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_delete_connectionstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=44, null=True, unique=True),
        ),
    ]
