# Generated by Django 4.2.4 on 2024-01-24 17:41

import core.utils.models_helpers
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0044_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilehaspublication",
            name="user_profile",
            field=core.utils.models_helpers.SlugFieldForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="slug",
            ),
        ),
    ]
