# Generated by Django 4.2.4 on 2024-02-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0045_alter_profilehaspublication_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="continent_of_birth",
            field=models.CharField(
                choices=[
                    ("OC", "Oceania"),
                    ("EU", "Europe"),
                    ("AF", "Africa"),
                    ("NA", "North America"),
                    ("AN", "Antarctica"),
                    ("SA", "South America"),
                    ("AS", "Asia"),
                ],
                default="AN",
                max_length=15,
                null=True,
            ),
        ),
    ]
