[tool.poetry]
name = "stays"
version = "0.1.0"
description = ""
authors = ["nojoven <work.cedricjoseph@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
django = "^4.2.4"
psycopg = "^3.1.10"
pytest-cov = "^4.1.0"
requests-cache = "^1.1.0"
requests = "^2.31.0"
glom = "^23.3.0"
django-environ = "^0.11.2"
black = "^23.7.0"
arrow = "^1.2.3"
icecream = "^2.1.3"
stackprinter = "^0.2.10"
frosch = "^0.1.9"
sentry-sdk = "^1.40.0"
django-q2 = "^1.6.1"
pydantic = "^2.3.0"
isort = "^5.12.0"
flake8 = "^6.1.0"
django-cities-light = "^3.9.2"
django-friendship = "^1.9.6"
django-allauth = "^0.55.2"
django-allauth-ui = "^0.1.4"
django-widget-tweaks = "^1.5.0"
django-tinymce = "^3.6.1"
iommi = "^6.1.1"
django-formset = "^1.1"
django-el-pagination = "^4.0.0"
django-easy-maps = "^1.1.3"
django-htmx = "^1.16.0"
django-filer = "^3.0.5"
django-countries = {extras = ["pyuca"], version = "^7.5.1"}
django-bootstrap-datepicker-plus = "^5.0.4"
django-audiofield = "^0.10.1"
pillow = "^10.0.0"
whitenoise = "^6.5.0"
clean-text = "^0.6.0"
django-easy-validator = "^1.7.0"
djlint = "^1.32.1"
sorl-thumbnail = "^12.9.0"
django-email-blacklist = "^1.0.1"
django-auto-logout = "^0.5.1"
django-actistream = "^3.0.2"
django-filter = "^23.2"
django-defender = "^0.9.7"
tox-poetry = "^0.5.0"
django-test-plus = "^2.2.3"
django-test-migrations = "^1.3.0"
djet = "^0.3.0"
django-cookie-consent = "^0.4.0"
dynaconf = "^3.2.2"
django-configurations = "^2.4.1"
python-decouple = "^3.8"
django-watchman = "^1.3.0"
pytest-django = "^4.5.2"
pip = "^23.2.1"
django-apm = "^0.3.0"
djangorestframework = "^3.14.0"
django-select2 = "^8.1.2"
django-redis = "^5.4.0"
channels = {extras = ["daphne"], version = "^4.0.0"}
geoip2 = "^4.8.0"
faker = "^21.0.0"
faker-file = {extras = ["all"], version = "^0.17.11"}
social-auth-app-django = "^5.4.0"
django-machina = "^1.3.1"
django-cool-pagination = "^0.3.0"
django-ninja-extra = "^0.20.2"
# django-quill-editor = "^0.1.40"
django-throttle-requests = "^0.7.0"
better-exceptions = "^0.3.3"
django-currentuser = "^0.6.1"
fontawesomefree = "^6.5.1"
directory-tree = "^0.0.4"
neattext = "^0.1.3"
robotframework-browser = "^18.0.0"
sweetify =  "^2.3.1"

[tool.poetry.dev-dependencies]
python = ">=3.10,<4.0"
django = "^4.2.4"
psycopg = "^3.1.10"
pytest = "^7.4.1"
pytest-cov = "^4.1.0"
requests-cache = "^1.1.0"
requests = "^2.31.0"
glom = "^23.3.0"
django-environ = "^0.11.2"
black = "^23.7.0"
arrow = "^1.2.3"
icecream = "^2.1.3"
stackprinter = "^0.2.10"
frosch = "^0.1.9"
sentry-sdk = "^1.40.0"
django-q2 = "^1.6.1"
pydantic = "^2.3.0"
isort = "^5.12.0"
flake8 = "^6.1.0"
django-friendship = "^1.9.6"
django-allauth = "^0.55.2"
django-allauth-ui = "^0.1.4"
django-widget-tweaks = "^1.5.0"
django-tinymce = "^3.6.1"
iommi = "^6.1.1"
django-formset = "^1.1"
django-el-pagination = "^4.0.0"
django-cool-pagination = "^0.3.0"
django-easy-maps = "^1.1.3"
django-htmx = "^1.16.0"
django-filer = "^3.0.5"
django-countries = {extras = ["pyuca"], version = "^7.5.1"}
django-bootstrap-datepicker-plus = "^5.0.4"
django-audiofield = "^0.10.1"
pillow = "^10.0.0"
whitenoise = "^6.5.0"
clean-text = "^0.6.0"
django-easy-validator = "^1.7.0"
djlint = "^1.32.1"
sorl-thumbnail = "^12.9.0"
django-email-blacklist = "^1.0.1"
django-auto-logout = "^0.5.1"
django-actistream = "^3.0.2"
django-filter = "^23.2"
django-defender = "^0.9.7"
tox-poetry = "^0.5.0"
django-test-plus = "^2.2.3"
django-test-migrations = "^1.3.0"
djet = "^0.3.0"
django-cookie-consent = "^0.4.0"
dynaconf = "^3.2.2"
django-configurations = "^2.4.1"
python-decouple = "^3.8"
django-cities-light = "^3.9.2"
django-watchman = "^1.3.0"
pytest-django = "^4.5.2"
pip = "^23.2.1"
django-apm = "^0.3.0"
djangorestframework = "^3.14.0"
django-select2 = "^8.1.2"
django-redis = "^5.4.0"
channels = {extras = ["daphne"], version = "^4.0.0"}
geoip2 = "^4.8.0"
faker = "^21.0.0"
faker-file = {extras = ["all"], version = "^0.17.11"}
social-auth-app-django = "^5.4.0"
django-machina = "^1.3.1"
django-ninja-extra = "^0.20.2"
# django-quill-editor = "^0.1.40"
django-throttle-requests = "^0.7.0"
better-exceptions = "^0.3.3"
django-currentuser = "^0.6.1"
fontawesomefree = "^6.5.1"
directory-tree = "^0.0.4"
neattext = "^0.1.3"
robotframework-browser = "^18.0.0"
sweetify =  "^2.3.1"


[tool.pytest.ini_options]
pythonpath = "."
DJANGO_SETTINGS_MODULE = "stays.stays.settings"
testpaths = [
    "tests"
]
addopts = "--import-mode importlib"
allowlist_externals = "poetry"
# commands_pre = "poetry install"
commands = "poetry run pytest --import-mode importlib"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
