# Generated by Django 4.2.5 on 2023-10-08 17:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=core.models.uuid_generator, editable=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of your publication.", max_length=70, null=True
                    ),
                ),
                ("year_of_stay", models.IntegerField(default=1950, null=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Summarize your story.", max_length=170, null=True
                    ),
                ),
                ("date_of_post", models.DateTimeField(auto_now_add=True)),
                ("date_of_update", models.DateTimeField(auto_now=True)),
                ("location_of_stay", models.CharField(max_length=100, null=True)),
                ("location_flag_url", models.URLField(null=True)),
                ("location_map_url", models.URLField(null=True)),
                ("image", models.URLField(null=True)),
                ("upvotes_count", models.IntegerField(default=0, null=True)),
                (
                    "website_ranking",
                    models.IntegerField(default=float("-inf"), null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationHasLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationHasProfiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_upvote_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PublicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("voice", "voice"), ("text", "text")],
                        default="text",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("is_text", models.BooleanField(default=True)),
                ("is_voice", models.BooleanField(default=False)),
            ],
        ),
    ]
