# Generated by Django 4.2.5 on 2023-10-04 19:05

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=core.models.uuid_generator, editable=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of your publication.", max_length=70, null=True
                    ),
                ),
                ("year_of_stay", models.IntegerField(default=1950, null=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Summarize your story.", max_length=170, null=True
                    ),
                ),
                ("date_of_post", models.DateTimeField(auto_now_add=True)),
                ("date_of_update", models.DateTimeField(auto_now=True)),
                ("location_of_stay", models.CharField(max_length=100, null=True)),
                ("location_flag_url", models.URLField(null=True)),
                ("location_map_url", models.URLField(null=True)),
                ("image", models.URLField(null=True)),
                ("upvotes_count", models.IntegerField(default=0, null=True)),
                (
                    "website_ranking",
                    models.IntegerField(default=float("-inf"), null=True),
                ),
                (
                    "author_username",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("voice", "voice"), ("text", "text")],
                        default="text",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("is_text", models.BooleanField(default=True)),
                ("is_voice", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PublicationHasProfiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_upvote_count", models.IntegerField(default=0)),
                (
                    "publication_author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication_title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="title",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication_upvoter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvote_count",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationHasLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="locations.location",
                    ),
                ),
                (
                    "given_name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_name",
                        to="locations.location",
                    ),
                ),
                (
                    "publication_title",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.publication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="publication",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.publicationtype",
            ),
        ),
    ]
