# Generated by Django 4.2.4 on 2024-02-23 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PublicationType",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="city_name",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="reveal_city",
        ),
    ]
