# Generated by Django 4.2.5 on 2023-12-03 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="author_username",
            new_name="author",
        ),
    ]
