# Generated by Django 4.2.5 on 2023-12-10 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_author_username_publication_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="date_of_post",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="publication",
            old_name="date_of_update",
            new_name="updated_at",
        ),
    ]
