# Generated by Django 4.2.5 on 2023-12-10 17:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_date_of_post_publication_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="id",
        ),
        migrations.AlterField(
            model_name="publication",
            name="uuid",
            field=models.UUIDField(
                default=core.models.uuid_generator,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
