# Generated by Django 4.2.5 on 2023-12-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_publication_id_alter_publication_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="image",
            field=models.ImageField(
                default="blank-profile-picture.jpg",
                null=True,
                upload_to="contents_illustrations",
            ),
        ),
    ]
