# Generated by Django 4.2.5 on 2023-12-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_publication_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="image",
            field=models.ImageField(
                default="seals-6627197_1280.jpg",
                null=True,
                upload_to="contents_illustrations",
            ),
        ),
    ]
