# Generated by Django 4.2.5 on 2023-12-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_publication_text_story"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="author",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="content_type",
        ),
        migrations.AddField(
            model_name="publication",
            name="author_slug",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="author_username",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="voice_story",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/<django.db.models.fields.CharField>/%Y/%m/%d/",
            ),
        ),
    ]
