# Generated by Django 4.2.5 on 2023-12-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_publication_image_publication_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="author_slug",
            field=models.SlugField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="picture",
            field=models.ImageField(
                default="seals-6627197_1280.jpg",
                null=True,
                upload_to="uploads/<django.db.models.fields.SlugField>/%Y/%m/%d/<django.db.models.fields.UUIDField>/picture",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="text_story",
            field=models.TextField(
                help_text="Write your story.", max_length=170, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="voice_story",
            field=models.FileField(
                default=None,
                null=True,
                upload_to="uploads/voice/<django.db.models.fields.SlugField>/%Y/%m/%d/<django.db.models.fields.UUIDField>/",
            ),
        ),
    ]
