# Generated by Django 4.2.5 on 2023-12-24 15:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_publication_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="picture",
            field=models.ImageField(
                default="seals-6627197_1280.jpg",
                max_length=800,
                null=True,
                upload_to=core.models.picture_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="voice_story",
            field=models.FileField(
                default=None, null=True, upload_to=core.models.voice_story_upload_to
            ),
        ),
    ]
