# Generated by Django 4.2.5 on 2023-12-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_publication_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="website_ranking",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
