# Generated by Django 4.2.5 on 2023-12-25 15:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_publication_website_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="location_of_stay",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
