# Generated by Django 4.2.5 on 2023-12-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0017_rename_location_of_stay_publication_country_code_of_stay_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="season_of_stay",
            field=models.CharField(
                help_text="Title of your publication.", max_length=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="text_story",
            field=models.TextField(
                help_text="Write your story.", max_length=25000, null=True
            ),
        ),
    ]
