# Generated by Django 4.2.5 on 2023-12-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_gallery_publicationhasgallery"),
        ("locations", "0003_countryrecord_locationrecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationhaslocation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="locations.locationrecord",
            ),
        ),
        migrations.AlterField(
            model_name="publicationhaslocation",
            name="given_name",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_name",
                to="locations.locationrecord",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="publication",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.publication",
            ),
        ),
    ]
