# Generated by Django 4.2.4 on 2023-12-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_publicationhaslocation_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationHasUserGuess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="publicationhaslocation",
            name="category",
        ),
        migrations.RemoveField(
            model_name="publicationhaslocation",
            name="given_name",
        ),
        migrations.AddField(
            model_name="publication",
            name="city_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="reveal_city",
            field=models.BooleanField(default=False),
        ),
    ]
