# Generated by Django 4.2.4 on 2023-12-31 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_guess_publicationhasuserguess_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Guess",
        ),
        migrations.RemoveField(
            model_name="publicationhaslocation",
            name="publication_title",
        ),
        migrations.DeleteModel(
            name="PublicationHasUserGuess",
        ),
        migrations.AlterField(
            model_name="publication",
            name="upvotes_count",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Upvotes count cannot be negative."
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="PublicationHasLocation",
        ),
    ]
