# Generated by Django 4.2.4 on 2024-01-01 03:13

import core.models
import core.utils.models_helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0024_publicationupvote_delete_publicationhasvoter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageOfGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=core.models.gallery_upload_to)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SeasonHasPublication",
        ),
        migrations.DeleteModel(
            name="YearHasPublication",
        ),
        migrations.AddField(
            model_name="gallery",
            name="uuid",
            field=models.UUIDField(default=core.models.uuid_generator, editable=False),
        ),
        migrations.AddField(
            model_name="publicationhasgallery",
            name="gallery",
            field=core.utils.models_helpers.UUIDForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_publications",
                to="core.gallery",
            ),
        ),
        migrations.AddField(
            model_name="publicationhasgallery",
            name="publication",
            field=core.utils.models_helpers.UUIDForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_galleries",
                to="core.publication",
            ),
        ),
        migrations.AlterField(
            model_name="publicationupvote",
            name="upvote_profile",
            field=core.utils.models_helpers.SlugFieldForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="publicationhasgallery",
            unique_together={("publication", "gallery")},
        ),
        migrations.AddField(
            model_name="imageofgallery",
            name="gallery",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.gallery",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="images",
            field=models.ManyToManyField(
                related_name="gallery_images", to="core.imageofgallery"
            ),
        ),
    ]
