# Generated by Django 4.2.4 on 2024-01-04 21:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_imageofgallery_delete_seasonhaspublication_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="voice_story",
            field=models.FileField(
                blank=True, default=None, upload_to=core.models.voice_story_upload_to
            ),
        ),
    ]
