# Generated by Django 4.2.4 on 2024-01-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_publication_voice_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="text_story",
            field=models.TextField(
                blank=True, help_text="Write your story.", max_length=25000, null=True
            ),
        ),
    ]
