# Generated by Django 4.2.4 on 2024-01-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_publication_text_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="text_story",
            field=models.TextField(
                help_text="Write your story.", max_length=25000, null=True
            ),
        ),
    ]
