# Generated by Django 4.2.4 on 2024-01-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_publication_text_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationupvote",
            name="upvote_profile",
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
