# Generated by Django 4.2.4 on 2024-01-14 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_publicationupvote_upvote_profile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publicationupvote",
            unique_together={("publication", "upvote_profile")},
        ),
    ]
