# Generated by Django 4.2.4 on 2024-01-25 15:06

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_publicationupvote_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="text_story",
            field=django_quill.fields.QuillField(
                blank=True, help_text="Write your story.", max_length=25000, null=True
            ),
        ),
    ]
