# Generated by Django 4.2.4 on 2024-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
