# Generated by Django 4.2.4 on 2024-02-25 18:44

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_delete_publicationtype_remove_publication_city_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="published_from_country_code",
            field=django_countries.fields.CountryField(
                default="IN", max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="season_of_stay",
            field=models.CharField(
                help_text="Season of your publication.", max_length=6, null=True
            ),
        ),
    ]
