# Generated by Django 4.2.4 on 2024-02-28 16:17

import core.utils.models_helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_publication_published_from_country_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="voice_story",
            field=models.FileField(
                blank=True,
                default="default.mp3",
                help_text="Record your story.",
                max_length=1000,
                upload_to=core.utils.models_helpers.voice_story_upload_to,
            ),
        ),
    ]
