# Generated by Django 4.2.4 on 2024-02-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="motto",
            field=models.CharField(default="I LOVE THIS WEBSITE!", max_length=300),
        ),
        migrations.AlterField(
            model_name="profile",
            name="signature",
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
