# Generated by Django 4.2.4 on 2024-02-05 23:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import locations.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StayCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=locations.models.uuid_generator, editable=False
                    ),
                ),
                ("continent_name", models.CharField(null=True)),
                ("country_name", models.CharField(null=True)),
                (
                    "country_code_of_stay",
                    django_countries.fields.CountryField(max_length=2, null=True),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.publication",
                    ),
                ),
            ],
        ),
    ]
