# Generated by Django 4.2.5 on 2023-10-04 19:05

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import locations.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=locations.models.uuid_generator, editable=False
                    ),
                ),
                (
                    "location_given_name",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lattitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "continent_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AFR", "Africa"),
                            ("ASI", "Asia"),
                            ("EUR", "Europe"),
                            ("NAM", "North America "),
                            ("SAM", "South America"),
                            ("OCE", "Oceania"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("city_name", models.CharField(blank=True, max_length=50, null=True)),
                ("area_name", models.CharField(blank=True, max_length=50, null=True)),
                ("region_name", models.CharField(blank=True, max_length=50, null=True)),
                ("ranking", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "wikipedia_url",
                    models.URLField(
                        blank=True, default="https://lemag.ird.fr/fr", null=True
                    ),
                ),
                ("interesting_data", models.TextField(blank=True, null=True)),
                ("has_flag", models.BooleanField(default=False)),
                ("flag_url", models.URLField(blank=True, null=True)),
                ("has_map", models.BooleanField(default=False)),
                ("map_url", models.URLField(blank=True, null=True)),
                ("celebrities_list", models.TextField(blank=True, null=True)),
                ("has_stays", models.BooleanField(default=False)),
                ("stays_count", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                "ordering": ["given_name"],
            },
        ),
        migrations.CreateModel(
            name="LocationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_city", models.BooleanField(default=False, null=True)),
                ("is_country", models.BooleanField(default=False, null=True)),
                ("is_area", models.BooleanField(default=False, null=True)),
                ("is_region", models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LocationWebData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_wiki_page", models.BooleanField(default=False)),
                ("has_wiki_summary", models.BooleanField(default=False)),
                (
                    "wikipedia_url",
                    models.URLField(
                        blank=True, default="https://lemag.ird.fr/fr", null=True
                    ),
                ),
                ("wiki_summary", models.TextField(null=True)),
                (
                    "wiki_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("wiki_interesting_data", models.TextField(blank=True, null=True)),
                ("wiki_flag_url", models.URLField(blank=True, null=True)),
                ("wiki_map_url", models.URLField(blank=True, null=True)),
                ("google_map_url", models.URLField(blank=True, null=True)),
                ("wiki_celebrities_list", models.TextField(blank=True, null=True)),
                (
                    "location_given_name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationHasProfileActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_upvotes_count", models.IntegerField(default=0)),
                (
                    "location_given_name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="location_category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.locationcategory",
            ),
        ),
    ]
