# Generated by Django 4.2.5 on 2023-12-29 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_countryrecord_locationrecord_and_more"),
        ("core", "0021_alter_publicationhaslocation_category_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AlterUniqueTogether(
            name="cityrecord",
            unique_together={
                ("region", "subregion", "name"),
                ("region", "subregion", "slug"),
            },
        ),
    ]
