# Generated by Django 4.2.4 on 2024-01-01 03:13

import core.utils.models_helpers
from django.db import migrations, models
import django.db.models.deletion
import locations.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_imageofgallery_delete_seasonhaspublication_and_more"),
        ("locations", "0007_alter_upvotecountryranking_country_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staycountry",
            name="country_code_of_stay",
        ),
        migrations.AddField(
            model_name="challengeattempt",
            name="uuid",
            field=models.UUIDField(
                default=locations.models.uuid_generator, editable=False
            ),
        ),
        migrations.AddField(
            model_name="staychallenge",
            name="uuid",
            field=models.UUIDField(
                default=locations.models.uuid_generator, editable=False
            ),
        ),
        migrations.AddField(
            model_name="staycountry",
            name="publication",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.publication",
            ),
        ),
        migrations.AlterField(
            model_name="attempthaslocationchallenge",
            name="attempt",
            field=core.utils.models_helpers.UUIDForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.challengeattempt",
            ),
        ),
        migrations.AlterField(
            model_name="attempthaslocationchallenge",
            name="challenge",
            field=core.utils.models_helpers.UUIDForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.staychallenge",
            ),
        ),
    ]
