# Generated by Django 4.2.4 on 2024-01-01 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0008_remove_staycountry_country_code_of_stay_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempthaslocationchallenge",
            name="attempt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.challengeattempt",
            ),
        ),
        migrations.AlterField(
            model_name="attempthaslocationchallenge",
            name="challenge",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.staychallenge",
            ),
        ),
    ]
