# Generated by Django 4.2.4 on 2024-01-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0010_challengeattempt_incrementation_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staycountry",
            name="country_code_of_stay",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
