# Generated by Django 4.2.4 on 2024-01-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0012_alter_staycountry_country_code_of_stay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staycountry",
            name="continent_name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="staycountry",
            name="country_name",
            field=models.CharField(null=True),
        ),
    ]
