# Generated by Django 4.2.4 on 2024-01-07 14:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0013_alter_staycountry_continent_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staycountry",
            name="country_code_of_stay",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
